image: webdevops/php-nginx:debian-8-php7

services:
  - mysql

before_script:
  - bash ci/docker_install.sh > /dev/null

standard:
  script:
  - composer install --no-interaction --no-progress
  - ./vendor/bin/phploc src/
  - ./vendor/bin/phpcpd src/
  - ./vendor/bin/phpunit -c ci/phpunit.xml
  - ./vendor/bin/phpcs src/ tests/ --standard=PSR2
  - ./vendor/bin/phpmd src/,tests/ text ci/phpmd.xml
