image: webdevops/php-nginx:debian-8-php7

services:
  - mysql

before_script:
  - bash ci/docker_install.sh > /dev/null

test:app:
  script:
  - composer install --no-interaction --no-progress
  - vendor/bin/phpunit -c ci/phpunit.xml
